---
- name: First Error Handling
  hosts: planetexpress
  gather_facts: false  # we won't be using any facts
  connection: ssh    # this is the default connection type for Ansible

  tasks:
    
    - name: A block is simply a group of tasks
      block: 
       
       - name: The first task 
         shell: "echo 'My single task ran' > example.txt"
       
       - name: The second task
         shell: "echo 'My second task ran' >> example.txt"
       
       - name: The third task
         shell: "echo 'My third task ran' >> example.txt"  

