---
- name: Playbook with Precheck Role
  hosts: arista_switches        # group within the inventory to match on
  connection: network_cli       # required when connecting to switch devices
  become: yes
  become_method: enable
  gather_facts: yes             # this defines ansible_facts
                            # (it runs *_facts on the target network switches)

  tasks:
  - name: Import the precheck role
    import_role:
      name: precheck

